# Distributed under the OSI-approved BSD 3-Clause License.
# See accompanying file LICENSE.txt for details.

name: get-language-list-from-languages-file

description: Get the Language List from languages.json

inputs:
  language:
    required: true    # [required]
    description: xxx
  all-in-one:
    required: false
    description: xxx
    default: 'true'
  languages-file:
    required: false
    description: xxx
    default: 'languages.json'
  working-directory:
    required: false
    description: The directory from which to run commands or locate files.
    default: ${{ github.workspace }}

outputs:
  LANGUAGE_NUM:
    value: ${{ steps.glll.outputs.LANGUAGE_NUM }}
    description: xxx
  LANGUAGE_LIST:
    value: ${{ steps.glll.outputs.LANGUAGE_LIST }}
    description: xxx

runs:
  using: composite
  steps:
    - name: Get the Language List from languages.json
      id: glll
      shell: bash
      run: |
        LANGUAGE="${{ inputs.language }}"
        ALL_IN_ONE="${{ inputs.all-in-one }}"
        LANGUAGES_FILE="${{ inputs.languages-file }}"
        WORKING_DIRECTORY=$(echo "${{ inputs.working-directory }}" | sed 's#\\#/#g' | sed 's#^\([A-Za-z]\):#/\L\1#')

        cd ${WORKING_DIRECTORY}

        if [[ "${LANGUAGE}" == "all" ]]; then
          if [[ "${ALL_IN_ONE}" == "true" ]]; then
            LANGUAGE_LIST="[ \"all\" ]"
          elif [[ "${ALL_IN_ONE}" == "false" ]]; then
            JQ_FILTER="keys"
            JQ_FILE="${LANGUAGES_FILE}"
            LANGUAGE_LIST=$(jq -c "${JQ_FILTER}" "${JQ_FILE}")
          else
            echo "Error: Invalid ALL_IN_ONE value. (${ALL_IN_ONE})" >&2
            exit 1
          fi
        else
          JQ_FILTER="keys[]"
          JQ_FILE="${LANGUAGES_FILE}"
          LANGUAGE_LINES=($(jq -r "${JQ_FILTER}" "${JQ_FILE}" | tr -d '\r'))
          FOUND_LANGUAGE=false
          for LANGUAGE_LINE in ${LANGUAGE_LINES[@]}; do
            if [[ "${LANGUAGE_LINE}" == "${LANGUAGE}" ]]; then
              FOUND_LANGUAGE=true
              LANGUAGE_LIST="[ \"${LANGUAGE}\" ]"
              break
            fi
          done
          if [[ "${FOUND_LANGUAGE}" == "true" ]]; then
            echo "Language '${LANGUAGE}' is found in the list."
          else
            echo "Error: Language '${LANGUAGE}' is NOT found in the list." >&2
            exit 1
          fi
        fi
        LANGUAGE_NUM=$(jq "length" <<< "${LANGUAGE_LIST}")

        echo "LANGUAGE_NUM=${LANGUAGE_NUM}" >> ${GITHUB_OUTPUT}
        echo "LANGUAGE_NUM:"
        echo "${LANGUAGE_NUM}"

        echo "LANGUAGE_LIST=${LANGUAGE_LIST}" >> ${GITHUB_OUTPUT}
        echo "LANGUAGE_LIST:"
        echo "${LANGUAGE_LIST}" | jq "."
