name: ci-mirror-repository

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: '20 20 * * *'

jobs:
  check-preconditions:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ join(steps.*.outcome) }}
    steps:
      - id: secrets
        continue-on-error: true
        run: '[ -n "$SSH_PRIVATE_KEY" ]'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      SERVER_LIST: ${{ steps.gvl.outputs.SERVER_LIST }}
    steps:
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Get SERVER_LIST from mirrors.json
        id: gvl
        shell: bash
        run: |
          JQ_FILE="mirrors.json"
          JQ_FILTER=".mirrors | map(.SERVER)"
          SERVER_LIST=$(jq -c "${JQ_FILTER}" "${JQ_FILE}")
          echo "SERVER_LIST=${SERVER_LIST}" >> ${GITHUB_OUTPUT}
          echo "SERVER_LIST:"
          echo "${SERVER_LIST}" | jq "."

  matrix:
    needs: get-matrix
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.SERVER }}
      cancel-in-progress: true
    strategy:
      matrix: 
        SERVER: ${{ fromJSON(needs.get-matrix.outputs.SERVER_LIST) }}
      fail-fast: false
    uses: ./.github/workflows/use-mirror-repository.yml
    with:
      GIT_TARGET_SERVER: ${{ matrix.SERVER }}
      GIT_TARGET_REPO: ${{ github.repository }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
