name: ci-mirror-repository

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: '20 20 * * *'

jobs:
  check-preconditions:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ join(steps.*.outcome) }}
    steps:
      - id: secrets
        continue-on-error: true
        run: '[ -n "$SSH_PRIVATE_KEY" ]'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  to-gitlab:
    needs: check-preconditions
    if: '!contains(needs.check-preconditions.outputs.results, "failure")'
    runs-on: ubuntu-latest
    steps:
      - name: Check contexts
        run: |
          echo "github.repository = ${{ github.repository }}"
          echo "github.event.repository.name = ${{ github.event.repository.name }}"
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0  # 0 indicates all history for all branches and tags.
      - name: Mirror to GitLab
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@gitlab.com:${{ github.repository }}.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  to-gitee:
    needs: check-preconditions
    if: '!contains(needs.check-preconditions.outputs.results, "failure")'
    runs-on: ubuntu-latest
    steps:
      - name: Check contexts
        run: |
          echo "github.repository = ${{ github.repository }}"
          echo "github.event.repository.name = ${{ github.event.repository.name }}"
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0  # 0 indicates all history for all branches and tags.
      - name: Mirror to Gitee
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@gitee.com:${{ github.repository }}.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  to-gitflic:
    needs: check-preconditions
    if: '!contains(needs.check-preconditions.outputs.results, "failure")'
    runs-on: ubuntu-latest
    steps:
      - name: Check contexts
        run: |
          echo "github.repository = ${{ github.repository }}"
          echo "github.event.repository.name = ${{ github.event.repository.name }}"
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0  # 0 indicates all history for all branches and tags.
      - name: Mirror to GitFlic
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@gitflic.ru:${{ github.repository }}.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  to-gitea:
    needs: check-preconditions
    if: '!contains(needs.check-preconditions.outputs.results, "failure")'
    runs-on: ubuntu-latest
    steps:
      - name: Check contexts
        run: |
          echo "github.repository = ${{ github.repository }}"
          echo "github.event.repository.name = ${{ github.event.repository.name }}"
      - name: Checkout to '${{ github.ref }}'
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0  # 0 indicates all history for all branches and tags.
      - name: Mirror to Gitea
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@gitea.com:${{ github.repository }}.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
