name: mirror-github-to-gitee

on:
  push:
  pull_request_target:
    branches: [master]
  workflow_dispatch:

jobs:
  mirror-github-to-gitee:
    name: Mirror from GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: |
          echo "secrets.GITEE_PRIVATE_KEY = ${{ secrets.GITEE_PRIVATE_KEY }}"
          echo "secrets.GITEE_TOKEN = ${{ secrets.GITEE_TOKEN }}"

      - name: Checkout to ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: Yikun/hub-mirror-action@master
        with:
          src: github/hwhsu1231
          dst: gitee/hwhsu1231
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: 'demo-github-gitee-mirror'
          force_update: true
