name: 'GitHub Actions Mirror'

on:
  workflow_dispatch:
#  push:
#    branches: 
#      - master
  schedule:
    - cron: '20 20 * * *'

jobs:
  # mirror_to_gitlab:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout to ${{ github.ref }}
  #       uses: actions/checkout@v3.3.0
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Mirror to gitlab
  #       uses: pixta-dev/repository-mirroring-action@v1.1.1
  #       with:
  #         target_repo_url:
  #           git@gitlab.com:hwhsu1231/demo-github-gitee-mirror.git
  #         ssh_private_key:
  #           ${{ secrets.GITEE_PRIVATE_KEY }}

  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to ${{ github.ref }}
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Echo something
        run: |
          echo "github.event.repository.name = ${{ github.event.repository.name }}"
          echo "github.repository = ${{ github.repository }}"

      - name: Mirror to Gitee
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            # git@gitee.com:hwhsu1231/demo-github-gitee-mirror.git
            git@gitee.com:${{ github.repository }}.git
          ssh_private_key:
            ${{ secrets.GITEE_PRIVATE_KEY }}
