name: Tests / test-user-mirror

on:
  push:
  pull_request_target:
    branches: [master]
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Mirror Github to Gitee with the current repo
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/hwhsu1231
          dst: gitee/hwhsu1231
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: '${{ env.GITHUB_REPOSITORY }}'
          # white_list: ${{ env.GITHUB_REPOSITORY }}
          # force_update: true
          # debug: true
          # mappings: 'hashes=>hashes_gitee'
